// <auto-generated />
using System;
using FastFoodWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FastFoodWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260628053805_AddPaymentFields")]
    partial class AddPaymentFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FastFoodWeb.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Burger"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Gà rán"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pizza"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Đồ uống"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Tráng miệng"
                        });
                });

            modelBuilder.Entity("FastFoodWeb.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VnPayTxnRef")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FastFoodWeb.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("FastFoodWeb.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Burger bò Úc xay thủ công, sốt đặc biệt, rau tươi giòn.",
                            ImageUrl = "/images/smartburger.jpg",
                            IsAvailable = true,
                            IsFeatured = true,
                            Name = "Smash Burger Bò",
                            Price = 149000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Đùi gà chiên giòn, sốt mayo tỏi, dưa leo tươi.",
                            ImageUrl = "/images/burgergagion.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Burger Gà Giòn",
                            Price = 129000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Gà rán vàng giòn theo công thức gia truyền, kèm sốt chua ngọt.",
                            ImageUrl = "/images/garan2mieng.jpg",
                            IsAvailable = true,
                            IsFeatured = true,
                            Name = "Gà Rán 2 Miếng",
                            Price = 99000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Cánh gà chiên ngập dầu, phủ sốt mắm tỏi ớt đậm đà.",
                            ImageUrl = "/images/canhgachienmam.png",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Cánh Gà Chiên Mắm",
                            Price = 79000m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Pizza đế mỏng, topping tôm mực bạch tuộc, phô mai kéo sợi.",
                            ImageUrl = "/images/pizzahaisan.png",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Pizza Hải Sản",
                            Price = 199000m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Thịt bò nướng BBQ, hành tây, ớt chuông, sốt đặc biệt.",
                            ImageUrl = "/images/pizzabo.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Pizza Bò BBQ",
                            Price = 189000m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Description = "Coca Cola lon 330ml, uống lạnh cực đã.",
                            ImageUrl = "/images/cocacola.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Coca Cola",
                            Price = 25000m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Khoai tây cắt sợi chiên vàng giòn, muối tiêu, chấm tương ớt.",
                            ImageUrl = "/images/khoaitay.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Khoai Tây Chiên Vừa",
                            Price = 39000m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Description = "Bánh chocolate nóng chảy bên trong, ăn kèm kem vani.",
                            ImageUrl = "/images/banhlava.jpg",
                            IsAvailable = true,
                            IsFeatured = true,
                            Name = "Bánh Lava Nutella",
                            Price = 89000m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "Bánh mì cuộn gà nướng teriyaki, rau xà lách, cà rốt bào.",
                            ImageUrl = "/images/wrapga.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Wrap Gà Teriyaki",
                            Price = 109000m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "Hai lớp thịt bò, hai lớp phô mai Cheddar tan chảy, dưa leo muối.",
                            ImageUrl = "/images/doublecheese.jpg",
                            IsAvailable = true,
                            IsFeatured = true,
                            Name = "Double Cheese Burger",
                            Price = 169000m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Description = "Tôm sú tẩm bột tempura chiên giòn, sốt Thousand Island, xà lách.",
                            ImageUrl = "/images/bugertom.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Burger Tôm Tempura",
                            Price = 139000m,
                            Stock = 70
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            Description = "Burger bò kèm nấm xào bơ tỏi và phô mai Swiss béo ngậy.",
                            ImageUrl = "/images/mushroomswissburger.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Mushroom Swiss Burger",
                            Price = 159000m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = "Miếng gà rán bọc lớp phô mai cheddar chảy vàng bên ngoài.",
                            ImageUrl = "/images/garanphomai.jpg",
                            IsAvailable = true,
                            IsFeatured = true,
                            Name = "Gà Rán Phô Mai",
                            Price = 115000m,
                            Stock = 90
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Description = "Cánh gà chiên giòn sốt cam mật ong chua ngọt, thơm lừng.",
                            ImageUrl = "/images/canhgasotcam.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Cánh Gà Sốt Cam",
                            Price = 89000m,
                            Stock = 75
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Description = "Đùi gà ướp BBQ nướng than hoa, da giòn, thịt mềm thấm gia vị.",
                            ImageUrl = "/images/ganuongbbq.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Đùi Gà Nướng BBQ",
                            Price = 95000m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            Description = "Bốn loại phô mai Mozzarella, Cheddar, Parmesan, Gorgonzola tan chảy.",
                            ImageUrl = "/images/pizza4phomai.jpg",
                            IsAvailable = true,
                            IsFeatured = true,
                            Name = "Pizza 4 Phô Mai",
                            Price = 219000m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Description = "Ức gà nướng, nấm đông cô, hành tây caramel, sốt kem trắng.",
                            ImageUrl = "/images/pizzaganam.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Pizza Gà Nấm",
                            Price = 179000m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 3,
                            Description = "Xúc xích Pepperoni, ớt chuông nhiều màu, olive đen, sốt cà.",
                            ImageUrl = "/images/pizzay.png",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Pizza Xúc Xích Ý",
                            Price = 185000m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Description = "Trà sữa Đài Loan đậm đà, trân châu đen dẻo, đá lạnh.",
                            ImageUrl = "/images/trasuachanchau.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Trà Sữa Trân Châu",
                            Price = 45000m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            Description = "Dâu tây tươi xay nhuyễn, sữa tươi không đường, đá bào mịn.",
                            ImageUrl = "/images/sinhtodau.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Sinh Tố Dâu",
                            Price = 49000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            Description = "Cam Valencia ép tươi nguyên chất, không thêm đường, giàu vitamin C.",
                            ImageUrl = "/images/nuoccamep.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Nước Cam Ép",
                            Price = 39000m,
                            Stock = 120
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            Description = "Kem Gelato Ý làm từ dâu tươi, vị béo mịn, ít ngọt thanh mát.",
                            ImageUrl = "/images/gelatodau.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Kem Gelato Dâu",
                            Price = 55000m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            Description = "Cheesecake New York đế bánh quy giòn, mặt phủ compote việt quất.",
                            ImageUrl = "/images/cheesecakevq.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Cheesecake Việt Quất",
                            Price = 75000m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            Description = "Donut chiên phồng, phủ ganache chocolate đen, rắc sprinkles màu.",
                            ImageUrl = "/images/donutsocola.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Bánh Donut Sô Cô La",
                            Price = 35000m,
                            Stock = 100
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FastFoodWeb.Models.OrderDetail", b =>
                {
                    b.HasOne("FastFoodWeb.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastFoodWeb.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FastFoodWeb.Models.Product", b =>
                {
                    b.HasOne("FastFoodWeb.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FastFoodWeb.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("FastFoodWeb.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
